name: Update Content Timestamps

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run update script
        run: node generate-updates-json.js

      - name: Commit and push updates.json
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add updates.json
          git commit -m "📦 Auto-update content timestamps" || echo "No changes to commit"
          git push
